version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: gonamer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gonamer
    main: ./cmd/gonamer/main.go
    flags: -trimpath
    ldflags: |
      -s -w
      -X main.version={{.Version}}
      -X main.commit={{.Commit}}
      -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: gonamer
    package_name: gonamer
    vendor: nouuu
    homepage: https://github.com/nouuu/gonamer
    maintainer: nouuu <noelarrieulacoste@yahoo.fr>
    description: Automatic media file renamer using TMDB API
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    suggests:
      - make
    section: utils
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/gonamer/LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^vendor:"
  groups:
    - title: '🚀 Features'
      regexp: ".*feat.*:.*"
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: ".*fix.*:.*"
      order: 1
    - title: '✨ Improvements'
      regexp: ".*enhancement.*:.*"
      order: 3
    - title: '📚 Documentation'
      regexp: ".*docs.*:.*"
      order: 4
    - title: '🔧 Maintenance'
      regexp: ".*chore.*:.*"
      order: 5
    - title: '👷 CI/CD'
      regexp: ".*ci.*:.*"
      order: 6
    - title: '🔍 Other Changes'
      order: 999

release:
  draft: false
  prerelease: auto
  name_template: "GoNamer v{{.Version}}"

  header: |
    ## GoNamer Release v{{.Version}} 🚀
    
    Automatic media file renamer using TMDB API.

  footer: |
    ### Quick Start
    
    **Homebrew Tap**
    ```bash
    brew install nouuu/tap/gonamer
    ```
    
    **Go Install**
    ```bash
    go install github.com/nouuu/gonamer/cmd/gonamer@v{{.Version}}
    ```
    
    ### Package Managers
    - **Debian/Ubuntu**: Download `.deb` package below
    - **RHEL/Fedora**: Download `.rpm` package below
    - **Alpine**: Download `.apk` package below
    - **Arch Linux**: Download `.pkg.tar.zst` package below
    
    ### Binaries
    **Linux**
    - `gonamer_Linux_x86_64.tar.gz`
    - `gonamer_Linux_arm64.tar.gz`
    
    **macOS (Darwin)**
    - `gonamer_Darwin_x86_64.tar.gz`
    - `gonamer_Darwin_arm64.tar.gz`
    
    **Windows**
    - `gonamer_Windows_x86_64.zip`
    - `gonamer_Windows_arm64.zip`
    
    ### Verify Installation
    
    ```bash
    # Verify SHA-256 checksums
    sha256sum -c checksums.txt
    ```
    
    ### Additional Resources
    - [📚 Documentation](https://github.com/nouuu/gonamer#readme)
    - [🐛 Issue Tracker](https://github.com/nouuu/gonamer/issues)
    - [💡 Feature Requests](https://github.com/nouuu/gonamer/issues/new)
    
    ---
    If you find GoNamer useful, please consider giving it a ⭐️